from django.conf.urls import url

from .views import (
    add_editorial_review,
    download_editor_er_file,
    download_er_file,
    editorial_review,
    editorial_review_thanks,
    editorial_reviewer_email_editor,
    EditorialReviewCompletionEmail,
    email_editorial_review,
    remove_editorial_review,
    update_editorial_review_due_date,
    view_content_summary,
    view_editorial_review,
    view_non_editorial_review,
    withdraw_editorial_review,
)

urlpatterns = [
   url(
        r'(?P<submission_type>[-\w]+)/(?P<submission_id>\d+)/add/$',
        add_editorial_review,
        name='add_editorial_review'
   ),
   url(
        r'download/(?P<file_id>\d+)/review/(?P<review_id>\d+)/editor/$',
        download_editor_er_file,
        name='download_editor_er_file'
   ),
   url(
        r'download/(?P<file_id>\d+)/review/(?P<review_id>\d+)/$',
        download_er_file,
        name='download_er_file'
   ),
   url(
        r'editor/view/(?P<review_id>\d+)/$',
        view_editorial_review,
        name='view_editorial_review'
   ),
   url(
        r'remove/(?P<review_id>\d+)/$',
        remove_editorial_review,
        name='remove_editorial_review'
   ),
   url(
        r'withdraw/(?P<review_id>\d+)/$',
        withdraw_editorial_review,
        name='withdraw_editorial_review'
   ),
   url(
        r'update_due_date/(?P<review_id>\d+)/$',
        update_editorial_review_due_date,
        name='update_editorial_review_due_date'
   ),
   url(
        r'review/(?P<review_id>\d+)/view_review/'
        r'(?P<non_editorial_review_id>\d+)/$',
        view_non_editorial_review,
        name='view_non_editorial_review'
   ),
   url(
        r'review/(?P<review_id>\d+)/summary/$',
        view_content_summary,
        name='view_content_summary'
   ),
   url(
        r'review/(?P<review_id>\d+)/thanks/$',
        editorial_review_thanks,
        name='editorial_review_thanks'
   ),
   url(
        r'review/(?P<review_id>\d+)/completion_email/$',
        EditorialReviewCompletionEmail.as_view(),
        name='editorial_review_completion_email'
   ),
   url(
        r'review/(?P<review_id>\d+)/$',
        editorial_review,
        name='editorial_review'
   ),
   url(
        r'(?P<review_id>\d+)/email/$',
        email_editorial_review,
        name='email_editorial_review'
   ),
   url(
        r'(?P<review_id>\d+)/email/editor/$',
        editorial_reviewer_email_editor,
        name='editorial_reviewer_email_editor_not_logged_in'
   ),
   url(
        r'(?P<review_id>\d+)/email/editor/(?P<user_id>\d+)/$',
        editorial_reviewer_email_editor,
        name='editorial_reviewer_email_editor_logged_in'
   )
]
