# variables set while deploying
namespace: rua

replicaCount: 1

image:
  repository: upress/rua
  pullPolicy: Always

nameOverride: ""
fullnameOverride: "rua"

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: traefik
  path: /
