apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.metadata.name }}
  namespace: {{ .Values.namespace }} 
  labels:
    app: {{ include "rua.name" . }}
    chart: {{ include "rua.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      targetPort: http
      name: http
  selector:
    app: {{ include "rua.name" . }}
    release: {{ .Release.Name }}
